---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: pod-subnet
  namespace: kube-system
spec:
  NetworkID: kindnet
  NetworkType: ptp
---
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: default
spec:
  NetworkID: kindnet
  NetworkType: ptp
