---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: batch/v1
kind: Job
metadata:
  name: etcdctl-lte-s1u
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: etcdctl-lte-s1u
          image: quay.io/coreos/etcd:v3.3.20
          env:
            - name: ETCDCTL_API
              value: "2"
          command: ["etcdctl"]
          args:
            - --no-sync
            - '--endpoint=http://$(FLANNEL_ETCD_SERVICE_HOST):12379'
            - set
            - '/s1u/network/config'
            - '{ "Network": "172.21.0.0/24", "Backend": {"Type": "vxlan", "VNI": 4, "DirectRouting": true}}'
      restartPolicy: Never
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lte-s1u-flannel-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
      hostNetwork: true
      serviceAccountName: flannel
      initContainers:
        - name: install-cni
          image: quay.io/coreos/flannel:v0.12.0-amd64
          command:
            - cp
          args:
            - -f
            - /tmp/cni-configs/s1u.conf
            - /etc/cni/net.d/s1u.conf
          volumeMounts:
            - name: destination
              mountPath: /etc/cni/net.d
            - name: source
              mountPath: /tmp/cni-configs/
      containers:
        - name: kube-flannel
          image: quay.io/coreos/flannel:v0.12.0-amd64
          command:
            - /opt/bin/flanneld
          args:
            - --ip-masq
            - -subnet-file=/run/flannel/lte-s1u.env
            - -etcd-prefix=/s1u/network
            - '-etcd-endpoints=http://$(FLANNEL_ETCD_SERVICE_HOST):12379'
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          securityContext:
            privileged: false
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: run
              mountPath: /run/flannel
      volumes:
        - name: run
          hostPath:
            path: /run/flannel
        - name: destination
          hostPath:
            path: /etc/cni/net.d
        - name: source
          configMap:
            name: lte-s1u-flannel-cfg
