---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

kind: ConfigMap
apiVersion: v1
metadata:
  name: lte-euu-flannel-cfg
  namespace: kube-system
data:
  euu.conf: |
    {
      "name": "lte-euu",
      "cniVersion": "0.3.1",
      "type": "flannel",
      "subnetFile": "/run/flannel/lte-euu.env",
      "dataDir": "/var/lib/cni/flannel_euu",
      "delegate": {
        "bridge": "kbr1"
      }
    }
  net-conf.json: |
    {
      "Network": "10.0.3.0/24",
      "Backend": {
        "Type": "vxlan",
        "VNI": 2,
        "DirectRouting": true
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: lte-sgi-flannel-cfg
  namespace: kube-system
data:
  sgi.conf: |
    {
      "name": "lte-sgi",
      "cniVersion": "0.3.1",
      "type": "flannel",
      "subnetFile": "/run/flannel/lte-sgi.env",
      "dataDir": "/var/lib/cni/flannel_sgi",
      "delegate": {
        "bridge": "kbr2"
      }
    }
  net-conf.json: |
    {
      "Network": "10.0.1.0/24",
      "Backend": {
        "Type": "vxlan",
        "VNI": 3,
        "DirectRouting": true
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: lte-s1u-flannel-cfg
  namespace: kube-system
data:
  s1u.conf: |
    {
      "name": "lte-s1u",
      "cniVersion": "0.3.1",
      "type": "flannel",
      "subnetFile": "/run/flannel/lte-s1u.env",
      "dataDir": "/var/lib/cni/flannel_s1u",
      "delegate": {
        "bridge": "kbr3"
      }
    }
  net-conf.json: |
    {
      "Network": "172.21.0.0/24",
      "Backend": {
        "Type": "vxlan",
        "VNI": 4,
        "DirectRouting": true
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: lte-s1c-flannel-cfg
  namespace: kube-system
data:
  s1c.conf: |
    {
      "name": "lte-s1c",
      "cniVersion": "0.3.1",
      "type": "flannel",
      "subnetFile": "/run/flannel/lte-s1c.env",
      "dataDir": "/var/lib/cni/flannel_s1c",
      "delegate": {
        "bridge": "kbr4"
      }
    }
  net-conf.json: |
    {
      "Network": "172.21.1.0/24",
      "Backend": {
        "Type": "vxlan",
        "VNI": 5,
        "DirectRouting": true
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: lte-s11-flannel-cfg
  namespace: kube-system
data:
  s11.conf: |
    {
      "name": "lte-s11",
      "cniVersion": "0.3.1",
      "type": "flannel",
      "subnetFile": "/run/flannel/lte-s11.env",
      "dataDir": "/var/lib/cni/flannel_s11",
      "delegate": {
        "bridge": "kbr5"
      }
    }
  net-conf.json: |
    {
      "Network": "172.22.0.0/24",
      "Backend": {
        "Type": "vxlan",
        "VNI": 6,
        "DirectRouting": true
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: lte-s5u-flannel-cfg
  namespace: kube-system
data:
  s5u.conf: |
    {
      "name": "lte-s5u",
      "cniVersion": "0.3.1",
      "type": "flannel",
      "subnetFile": "/run/flannel/lte-s5u.env",
      "dataDir": "/var/lib/cni/flannel_s5u",
      "delegate": {
        "bridge": "kbr6"
      }
    }
  net-conf.json: |
    {
      "Network": "172.25.0.0/24",
      "Backend": {
        "Type": "vxlan",
        "VNI": 7,
        "DirectRouting": true
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: lte-s5c-flannel-cfg
  namespace: kube-system
data:
  s5c.conf: |
    {
      "name": "lte-s5c",
      "cniVersion": "0.3.1",
      "type": "flannel",
      "subnetFile": "/run/flannel/lte-s5c.env",
      "dataDir": "/var/lib/cni/flannel_s5c",
      "delegate": {
        "bridge": "kbr7"
      }
    }
  net-conf.json: |
    {
      "Network": "172.25.1.0/24",
      "Backend": {
        "Type": "vxlan",
        "VNI": 8,
        "DirectRouting": true
      }
    }
