---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: lte-network
spec:
  payload: IP
  matches:
    - match:
      sourceSelector:
        link: euu
      route:
        - destination:
          destinationSelector:
            app: enb-euu
    - match:
      sourceSelector:
        link: sgi
      route:
        - destination:
          destinationSelector:
            app: http-server-sgi
    - match:
      sourceSelector:
        link: s1u
      route:
        - destination:
          destinationSelector:
            app: sgw-s1u
    - match:
      sourceSelector:
        link: s1c
      route:
        - destination:
          destinationSelector:
            app: mme-s1c
    - match:
      sourceSelector:
        link: s11
      route:
        - destination:
          destinationSelector:
            app: sgw-s11
    - match:
      sourceSelector:
        link: s5u
      route:
        - destination:
          destinationSelector:
            app: pgw-s5u
    - match:
      sourceSelector:
        link: s5c
      route:
        - destination:
          destinationSelector:
            app: pgw-s5c
